name: HideRails
version: 0.6.0-SNAPSHOT
author: Nepta_
description: Plugin for hide rails, ladder, redstone, signs and iron_bars - By Nepta_
main: fr.lulucraft321.hiderails.HideRails
load: POSTWORLD
loadbefore: [HideRails]
commands:
  hiderails:
    aliases: [hr]
    description: Main command