name: HideRails
version: 0.7.4-SNAPSHOT
api-version: 1.13
author: Nepta_
description: Plugin for hide rails, ladder, redstone, signs and iron_bars - By Nepta_
main: fr.nepta.hiderails.HideRails
load: POSTWORLD
commands:
  hiderails:
    aliases: [hr]
    description: Main command
